//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"

namespace cbf.OCPPServer.Messages_OCPP201
{
    using System = global::System;

    



    /// <summary>
    /// This contains the reason for sending this message to the CSMS.
    /// <br/>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v12.0.0.0))")]
    public enum BootReasonEnumType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"ApplicationReset")]
        ApplicationReset = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"FirmwareUpdate")]
        FirmwareUpdate = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"LocalReset")]
        LocalReset = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"PowerUp")]
        PowerUp = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"RemoteReset")]
        RemoteReset = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"ScheduledReset")]
        ScheduledReset = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"Triggered")]
        Triggered = 6,

        [System.Runtime.Serialization.EnumMember(Value = @"Unknown")]
        Unknown = 7,

        [System.Runtime.Serialization.EnumMember(Value = @"Watchdog")]
        Watchdog = 8,

    }

    /// <summary>
    /// Charge_ Point
    /// <br/>urn:x-oca:ocpp:uid:2:233122
    /// <br/>The physical system where an Electrical Vehicle (EV) can be charged.
    /// <br/>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v12.0.0.0))")]
    public partial class ChargingStationType
    {
        [Newtonsoft.Json.JsonProperty("customData", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public CustomDataType CustomData { get; set; }

        /// <summary>
        /// Device. Serial_ Number. Serial_ Number
        /// <br/>urn:x-oca:ocpp:uid:1:569324
        /// <br/>Vendor-specific device identifier.
        /// <br/>
        /// </summary>
        [Newtonsoft.Json.JsonProperty("serialNumber", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public string SerialNumber { get; set; }

        /// <summary>
        /// Device. Model. CI20_ Text
        /// <br/>urn:x-oca:ocpp:uid:1:569325
        /// <br/>Defines the model of the device.
        /// <br/>
        /// </summary>
        [Newtonsoft.Json.JsonProperty("model", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(20)]
        public string Model { get; set; }

        [Newtonsoft.Json.JsonProperty("modem", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public ModemType Modem { get; set; }

        /// <summary>
        /// Identifies the vendor (not necessarily in a unique manner).
        /// <br/>
        /// </summary>
        [Newtonsoft.Json.JsonProperty("vendorName", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public string VendorName { get; set; }

        /// <summary>
        /// This contains the firmware version of the Charging Station.
        /// <br/>
        /// <br/>
        /// </summary>
        [Newtonsoft.Json.JsonProperty("firmwareVersion", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public string FirmwareVersion { get; set; }

    }

    /// <summary>
    /// Wireless_ Communication_ Module
    /// <br/>urn:x-oca:ocpp:uid:2:233306
    /// <br/>Defines parameters required for initiating and maintaining wireless communication with other devices.
    /// <br/>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v12.0.0.0))")]
    public partial class ModemType
    {
        [Newtonsoft.Json.JsonProperty("customData", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public CustomDataType CustomData { get; set; }

        /// <summary>
        /// Wireless_ Communication_ Module. ICCID. CI20_ Text
        /// <br/>urn:x-oca:ocpp:uid:1:569327
        /// <br/>This contains the ICCID of the modem’s SIM card.
        /// <br/>
        /// </summary>
        [Newtonsoft.Json.JsonProperty("iccid", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(20)]
        public string Iccid { get; set; }

        /// <summary>
        /// Wireless_ Communication_ Module. IMSI. CI20_ Text
        /// <br/>urn:x-oca:ocpp:uid:1:569328
        /// <br/>This contains the IMSI of the modem’s SIM card.
        /// <br/>
        /// </summary>
        [Newtonsoft.Json.JsonProperty("imsi", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(20)]
        public string Imsi { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v12.0.0.0))")]
    public partial class BootNotificationRequest
    {
        [Newtonsoft.Json.JsonProperty("customData", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public CustomDataType CustomData { get; set; }

        [Newtonsoft.Json.JsonProperty("chargingStation", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public ChargingStationType ChargingStation { get; set; } = new ChargingStationType();

        [Newtonsoft.Json.JsonProperty("reason", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public BootReasonEnumType Reason { get; set; }

    }


}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore  472
#pragma warning restore  114
#pragma warning restore  108
#pragma warning restore 3016
#pragma warning restore 8603