//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"

namespace cbf.OCPPServer.Messages_OCPP201
{
    using System = global::System;



    /// <summary>
    /// This field specifies the connector type.
    /// <br/>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v12.0.0.0))")]
    public enum ConnectorEnumType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"cCCS1")]
        CCCS1 = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"cCCS2")]
        CCCS2 = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"cG105")]
        CG105 = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"cTesla")]
        CTesla = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"cType1")]
        CType1 = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"cType2")]
        CType2 = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"s309-1P-16A")]
        S3091P16A = 6,

        [System.Runtime.Serialization.EnumMember(Value = @"s309-1P-32A")]
        S3091P32A = 7,

        [System.Runtime.Serialization.EnumMember(Value = @"s309-3P-16A")]
        S3093P16A = 8,

        [System.Runtime.Serialization.EnumMember(Value = @"s309-3P-32A")]
        S3093P32A = 9,

        [System.Runtime.Serialization.EnumMember(Value = @"sBS1361")]
        SBS1361 = 10,

        [System.Runtime.Serialization.EnumMember(Value = @"sCEE-7-7")]
        SCEE77 = 11,

        [System.Runtime.Serialization.EnumMember(Value = @"sType2")]
        SType2 = 12,

        [System.Runtime.Serialization.EnumMember(Value = @"sType3")]
        SType3 = 13,

        [System.Runtime.Serialization.EnumMember(Value = @"Other1PhMax16A")]
        Other1PhMax16A = 14,

        [System.Runtime.Serialization.EnumMember(Value = @"Other1PhOver16A")]
        Other1PhOver16A = 15,

        [System.Runtime.Serialization.EnumMember(Value = @"Other3Ph")]
        Other3Ph = 16,

        [System.Runtime.Serialization.EnumMember(Value = @"Pan")]
        Pan = 17,

        [System.Runtime.Serialization.EnumMember(Value = @"wInductive")]
        WInductive = 18,

        [System.Runtime.Serialization.EnumMember(Value = @"wResonant")]
        WResonant = 19,

        [System.Runtime.Serialization.EnumMember(Value = @"Undetermined")]
        Undetermined = 20,

        [System.Runtime.Serialization.EnumMember(Value = @"Unknown")]
        Unknown = 21,

    }





    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v12.0.0.0))")]
    public partial class ReserveNowRequest
    {
        [Newtonsoft.Json.JsonProperty("customData", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public CustomDataType CustomData { get; set; }

        /// <summary>
        /// Id of reservation.
        /// <br/>
        /// </summary>
        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        public int Id { get; set; }

        /// <summary>
        /// Date and time at which the reservation expires.
        /// <br/>
        /// </summary>
        [Newtonsoft.Json.JsonProperty("expiryDateTime", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset ExpiryDateTime { get; set; }

        [Newtonsoft.Json.JsonProperty("connectorType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ConnectorEnumType? ConnectorType { get; set; }

        [Newtonsoft.Json.JsonProperty("idToken", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public IdTokenType IdToken { get; set; } = new IdTokenType();

        /// <summary>
        /// This contains ID of the evse to be reserved.
        /// <br/>
        /// </summary>
        [Newtonsoft.Json.JsonProperty("evseId", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? EvseId { get; set; }

        [Newtonsoft.Json.JsonProperty("groupIdToken", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public IdTokenType GroupIdToken { get; set; }

    }


}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore  472
#pragma warning restore  114
#pragma warning restore  108
#pragma warning restore 3016
#pragma warning restore 8603